*** Variables ***
${Web_Testing_Url}    https://the-internet.herokuapp.com/login
${secure_page}        https://the-internet.herokuapp.com/secure
${testsite_width}     1200
${testsite_height}    768

${username_alert}     Your username is invalid!
${password_alert}     Your password is invalid!

${username}           tomsmith
${password}           SuperSecretPassword!
${username_wrong}     abc
${password_wrong}     123456
